### ISSUE TITLE
有沒有計劃加入報表訂閱(定時自動派送)功能

### ISSUE THREAD

**Issue by huazhenhz** [NoneDay/CellReport#5]
CellReport可否像JasperReports那樣，加入報表訂閱(定時自動派送)功能？目前可有此類的規劃？
謝謝！

**Comment by NoneDay** [comment]
现有规划是这样的：1、提供crud自动生成
2、提供pivot 功能，也就是简单bi。
关于定时生成报表和推送服务，是会考虑实现的。如果您有兴趣自己实现也可以。生成前端展现的代码，以及后端如何调用，都在源码里面。




---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年9月25日(周日) 下午4:19
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [NoneDay/CellReport] 有沒有計劃加入報表訂閱(定時自動派送)功能 (Issue #5)




 
CellReport可否像JasperReports那樣，加入報表訂閱(定時自動派送)功能？目前可有此類的規劃？
 謝謝！

**Comment by huazhenhz** [comment]
有瞭解，我們會靜候佳音，目前先關閉這個Issue。感謝啦！
